###
# Trading-Bots settings for the examples project.
###

tag: ExampleBots

dry_run: False

installed_bots:
  - example_bots.any_to_any
  - example_bots.example
  - example_bots.relative_orders
  - example_bots.simple_limit

logging:
  bots_root: bots
  filename: bots.log
  level:
    low: debug
    high: info

storage:
  name: json
  filename: store.json

timeout: 120

urls:
